# Generated by Django 2.2 on 2022-04-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220406_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
