# Generated by Django 2.2 on 2022-04-06 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220406_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='fullName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.FullName'),
        ),
    ]
