# Generated by Django 2.2 on 2022-04-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customerId',
            new_name='customer',
        ),
    ]
