# Generated by Django 2.2 on 2022-05-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20220507_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fullName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.FullName'),
        ),
    ]
