# Generated by Django 2.2 on 2022-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedbook',
            name='cartId',
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
