# Generated by Django 2.2 on 2022-05-02 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220502_2125'),
        ('product', '0005_auto_20220502_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbook',
            name='cartId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Cart'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='totalPrice',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
