# Generated by Django 2.2 on 2022-05-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220502_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedbook',
            old_name='bookId',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='orderedbook',
            old_name='cartId',
            new_name='cart',
        ),
    ]
