# Generated by Django 2.2 on 2022-05-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20220516_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbook',
            name='clothes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Clothes'),
        ),
        migrations.AddField(
            model_name='orderedbook',
            name='shoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Shoes'),
        ),
    ]
