# Generated by Django 2.2 on 2022-05-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20220517_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbook',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Book'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='clothes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Clothes'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='shoes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Shoes'),
        ),
    ]
