# Generated by Django 2.2 on 2022-04-13 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0013_auto_20220413_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('float', models.FloatField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('totalPrice', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Cart')),
                ('paymentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Payment')),
                ('shipmentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Shipment')),
            ],
        ),
    ]
