# Generated by Django 2.2 on 2022-05-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220501_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='float',
            new_name='price',
        ),
    ]
