# Generated by Django 2.2 on 2022-05-02 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220502_2105'),
        ('order', '0003_auto_20220502_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderedBook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.OrderedBook'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
