# Generated by Django 2.2 on 2022-05-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220502_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='orderedBook',
        ),
    ]
