# Generated by Django 2.2 on 2022-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220502_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='price',
            new_name='extra_price',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='extra_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.FloatField(null=True),
        ),
    ]
